name: zorro_sign_contacts
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  sqflite: null
  flutter_localizations:
    sdk: flutter
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  intl: ^0.17.0

  # Service locator
  get_it: ^7.1.3

  provider: ^6.0.0

  # Equatable
  equatable: ^2.0.3

  # Functional Programming
  dartz: ^0.10.0-nullsafety.2

  # Auto Route
  auto_route: ^3.2.4

  # For HTTP Api Calls
  http: ^0.13.3

  # UUID
  uuid: ^3.0.4

  #permission request plugin
  permission_handler: ^9.2.0

  #JSON Annotation
  json_annotation: 4.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  pedantic: ^1.11.0
  pattern_formatter: ^2.0.0
  #pattern_formatter: ^2.0.0
  # Format Strings
  sprintf: ^6.0.0
  interpolator: ^0.1.0

  # responsive ui
  responsive_sizer: 3.0.4+4

  # url launcher
  url_launcher: ^6.0.10
  # Load SVG Images
  flutter_svg: ^0.22.0

  # Date Picker
  # syncfusion_flutter_datepicker: ^19.3.47
  flutter_rounded_date_picker: 2.0.2

  # Connectivity
  connectivity_plus: ^1.1.0
  # flutter secure storage
  flutter_secure_storage: 4.2.1

  # Image Picker
  image_picker: ^0.8.5+3

  #Finap Helper Packages
  finap_validator: ^0.0.1
  finap_currency_helper: ^0.0.1
  finap_secure_shared_preferences: ^0.0.1
  finap_connectivity_helper: ^0.0.1
  finap_datetime_helper: ^0.0.3
  finap_device_info_helper: ^0.0.1
  finap_error_handling: ^0.0.1
  finap_serialization_helper: ^0.0.1
  finap_extensions: ^0.0.3
  finap_base_theme: ^0.0.9

  #Firebase
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_crashlytics: ^2.5.3
  firebase_analytics: ^9.1.2

  #Webview Flutter
  webview_flutter: ^3.0.1

  # Shimmer
  shimmer: ^2.0.0

  # SyncFusion Calendar
  syncfusion_flutter_calendar: ^20.1.47

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^3.2.3
  build_runner: null
  json_serializable: null
  mobx_codegen: ^2.0.3

  # Auto Size Text
  auto_size_text: ^3.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/gifs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_black.ttf
        - asset: assets/fonts/poppins_bold.ttf
        - asset: assets/fonts/poppins_extrabold.ttf
        - asset: assets/fonts/poppins_light.ttf
        - asset: assets/fonts/poppins_medium.ttf
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_semibold.ttf
        - asset: assets/fonts/poppins_thin.ttf

    - family: NotoSansSinhala
      fonts:
        - asset: assets/fonts/notosanssinhala_black.ttf
        - asset: assets/fonts/notosanssinhala_bold.ttf
        - asset: assets/fonts/notosanssinhala_extrabold.ttf
        - asset: assets/fonts/notosanssinhala_extralight.ttf
        - asset: assets/fonts/notosanssinhala_light.ttf
        - asset: assets/fonts/notosanssinhala_medium.ttf
        - asset: assets/fonts/notosanssinhala_regular.ttf
        - asset: assets/fonts/notosanssinhala_semibold.ttf
        - asset: assets/fonts/notosanssinhala_thin.ttf

    - family: IskPota
      fonts:
        - asset: assets/fonts/iskpota.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          anyMap: true
